--
-- Datos sobre avatares
--

--
-- Volcado de datos para la tabla `avatar`
--
INSERT INTO `avatar` (`idAvatar`, `avatar`) VALUES
-- Personaje
(1, 'img/personajeAvatar/arquera.png'),
(2, 'img/personajeAvatar/arqueraAtaque.png'),
(3, 'img/personajeAvatar/avatar.png'),
(4, 'img/personajeAvatar/avatar2.png'),
(5, 'img/personajeAvatar/avatar3.png'),
(6, 'img/personajeAvatar/avatar4.png'),
(7, 'img/personajeAvatar/avatar5.png'),
(8, 'img/personajeAvatar/cazador.jpg'),
(9, 'img/personajeAvatar/cazador2.jpg'),
(10, 'img/personajeAvatar/ciego.jpg'),
(11, 'img/personajeAvatar/darius.png'),
(12, 'img/personajeAvatar/draven.png'),
(13, 'img/personajeAvatar/elfo-lunar-hombre.png'),
(14, 'img/personajeAvatar/elfo-lunar-mujer.jpg'),
(15, 'img/personajeAvatar/enano.jpg'),
(16, 'img/personajeAvatar/enano_armadura.jpg'),
(17, 'img/personajeAvatar/enano_oro.jpg'),
(18, 'img/personajeAvatar/garen.png'),
(19, 'img/personajeAvatar/guerrero.jpg'),
(20, 'img/personajeAvatar/guerrero2.jpg'),
(21, 'img/personajeAvatar/humano.jpg'),
(22, 'img/personajeAvatar/katarina.jpg'),
(23, 'img/personajeAvatar/mago.jpg'),
(24, 'img/personajeAvatar/mago2.jpg'),
(25, 'img/personajeAvatar/mago3.jpg'),
(26, 'img/personajeAvatar/nigromante.jpg'),
(27, 'img/personajeAvatar/orco2.jpg'),
(28, 'img/personajeAvatar/orco3.jpg'),
(29, 'img/personajeAvatar/pantheon.png'),
(30, 'img/personajeAvatar/pikachu.jpg'),
(31, 'img/personajeAvatar/pirata.jpg'),
(32, 'img/personajeAvatar/robot-mujer.jpg'),
(33, 'img/personajeAvatar/sacerdote.jpg'),
(34, 'img/personajeAvatar/sacerdote2.jpg'),
(35, 'img/personajeAvatar/semielfo.jpg'),
(36, 'img/personajeAvatar/semielfo-hombre.jpg'),
(37, 'img/personajeAvatar/semielfo-mujer.jpg'),
(38, 'img/personajeAvatar/zed.png'),
-- Monstruos
(39, 'img/monstruoAvatar/alienBuda.png'),
(40, 'img/monstruoAvatar/banshee.jpg'),
(41, 'img/monstruoAvatar/bruja.jpg'),
(42, 'img/monstruoAvatar/calamar.png'),
(43, 'img/monstruoAvatar/cocodrilo.png'),
(44, 'img/monstruoAvatar/dragon.jpg'),
(45, 'img/monstruoAvatar/felhound.jpg'),
(46, 'img/monstruoAvatar/gigante_de_la_montana.jpg'),
(47, 'img/monstruoAvatar/gnoll.jpg'),
(48, 'img/monstruoAvatar/golemLava.jpg'),
(49, 'img/monstruoAvatar/hidraFuego.jpg'),
(50, 'img/monstruoAvatar/hombreRoca.jpg'),
(51, 'img/monstruoAvatar/jineteFantasma.jpg'),
(52, 'img/monstruoAvatar/jineteFantasma.png'),
(53, 'img/monstruoAvatar/kobold.jpg'),
(54, 'img/monstruoAvatar/kraken.jpg'),
(55, 'img/monstruoAvatar/lasantacompana.jpg'),
(56, 'img/monstruoAvatar/monstruoBosque.png'),
(57, 'img/monstruoAvatar/murcielago.jpg'),
(58, 'img/monstruoAvatar/murcielago2.jpg'),
(59, 'img/monstruoAvatar/nazgul.jpg'),
(60, 'img/monstruoAvatar/oso.png'),
(61, 'img/monstruoAvatar/perroDeUrco.jpg'),
(62, 'img/monstruoAvatar/perroUrco.jpg'),
(63, 'img/monstruoAvatar/pez.png'),
(64, 'img/monstruoAvatar/piranaGigante.jpg'),
(65, 'img/monstruoAvatar/quimera.jpg'),
(66, 'img/monstruoAvatar/rey_del_mal.png'),
(67, 'img/monstruoAvatar/reyDelMal.jpg'),
(68, 'img/monstruoAvatar/santaCompana.jpg'),
(69, 'img/monstruoAvatar/serpienteDePantano.jpg'),
(70, 'img/monstruoAvatar/tiburonBlanco.jpg'),
(71, 'img/monstruoAvatar/troll.jpg'),
(72, 'img/monstruoAvatar/wyrm.jpg'),
(73, 'img/monstruoAvatar/zed.jpg');

--
-- Relaciones entre `avatar` y `monstruoavatar`
--
INSERT INTO `monstruoavatar` (`idMonstruoAvatar`, `idMonstruo`, `idAvatar`) VALUES
(1, 1, 53),
(2, 2, 47),
(3, 3, 71),
(4, 4, 46),
(5, 5, 45),
(6, 6, 48),
(7, 7, 67),
(8, 8, 49),
(9, 9, 41),
(10, 10, 40),
(11, 11, 52),
(12, 12, 59),
(13, 13, 64),
(14, 14, 69),
(15, 15, 70),
(16, 16, 54),
(17, 17, 44),
(18, 18, 57),
(19, 19, 65),
(20, 20, 72);